Lockers/config/urls.py
from django.contrib import admin
from django.urls import path , include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", include("login.urls")),
    path("", TemplateView.as_view(template_name = "home.html"), name="home"),
]

from django.conf.urls.static import static
from config import settings

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

Lockers/login/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm

app_name="login"

urlpatterns = [
    path("create/", views.create, name="create"),  # 회원가입
    path("login/",views.user_login,name="login"),  # 로그인
    path("loginhome/", views.loginhome, name="loginhome"), # 로그인 후 홈화면
    path("detail/" , views.detail , name='detail'),  # 회원정보 조회
    path("update/" , views.user_update , name='update'), # 회원정보수정
    path("password_change/" ,views.change_password , name="password_change"), # 비밀번호변경
    path('user_base/', views.RecoveryIdView.as_view(), name='user_base'),  # 아이디 찾기
    path('id/find/', views.ajax_find_id_view, name='ajax_id'), 

]

Lockers/login/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import RegexValidator

# Create your models here.

class User(AbstractUser):
    emailNumberRegex = RegexValidator(regex=r'^[0-9a-zA-Z]([-_\.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_\.]?[0-9a-zA-Z])*\.[a-zA-Z]{2,3}$')
    email = models.EmailField(unique=True , validators=[emailNumberRegex], max_length=255)
    name = models.CharField(verbose_name="사용자이름" , max_length=50)
    phoneNumberRegex = RegexValidator(regex = r'^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')
    phone = models.CharField(validators = [phoneNumberRegex], max_length = 11, unique = True)

    def __str__(self):
        return self.name

Lockers/login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm , PasswordChangeForm

from .models import User

class CustomUserCreateForm(UserCreationForm):
    
    password1 = forms.CharField(label='비밀번호' , widget=forms.PasswordInput())
    password2 = forms.CharField(label="비밀번호 확인",
                                widget=forms.PasswordInput(),
                                help_text="비밀번호 확인을 위해 이전과 동일한 비밀번호를 입력하세요.")
    phone = forms.CharField(label="전화번호" , help_text="'-'는 빼고 입력하세요")
    
    class Meta:
        model = User
        fields =['username','password1','password2','name','email','phone']

from django import forms
from django.contrib.auth.forms import UserChangeForm
from .models import User

class CustomUserChangeForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ['username', 'name', 'email', 'phone']

    def __init__(self, *args, **kwargs):
        super(CustomUserChangeForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.HiddenInput()

# 사용자 정보 및 비밀번호 변경 폼
class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="기존 패스워드",
        widget=forms.PasswordInput()
    )
    new_password1 = forms.CharField(
        label="새 패스워드",
        widget=forms.PasswordInput()
    )
    new_password2 = forms.CharField(
        label="새 패스워드 확인",
        widget=forms.PasswordInput()
    )

class RecoveryIdForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput,)
    email = forms.EmailField(widget=forms.EmailInput,)

    class Meta:
        fields = ['name', 'email']

    def __init__(self, *args, **kwargs):
        super(RecoveryIdForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = '이름'
        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
            'id': 'form_name',
        })
        self.fields['email'].label = '이메일'
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'id': 'form_email' 
        })

Lockers/login/views.py
from django.shortcuts import render , redirect
from django.urls import reverse
from .models import User

from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreateForm

from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import update_session_auth_hash

# Create your views here.

def create(request):
    if request.method == 'GET':
        return render(
            request,
            "login/create.html",
            {"form":CustomUserCreateForm()}
        )
    elif request.method == "POST":
        form = CustomUserCreateForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect(reverse('home'))
        else:
            return render(request, "login/create.html",{"form":form})

def user_login(request):
    if request.method == "GET":
        return render(request,
                      'login/login.html',
                      {'form':AuthenticationForm()})
    elif request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username , password=password)
        if user is not None :
            login(request, user)
            return redirect(reverse('login:loginhome'))
        else :
            return render(
                request,
                'login/login.html',
                {'form': AuthenticationForm(),
                "errorMessage":"ID나 Password를 다시 확인하세요."}
            )
        
@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse("home"))

@login_required
def loginhome(request):
    if request.method =="GET":
        return render(request,'login/loginhome.html')

@login_required
def user_update(request):
    if request.method == "GET":
        form = CustomUserChangeForm(instance = request.user)
        return render(request, "login/update.html", {"form":form})
    elif request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance = request.user)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request , user)
            return redirect(reverse('login:detail'))
        else:
            return render(request, "login/update.html", {"from" : form})
@login_required
def detail(request):
    user = User.objects.get(pk=request.user.pk)
    return render(request, "login/detail.html", {"object":user})

from django.contrib import messages
from .forms import CustomUserChangeForm, CustomPasswordChangeForm

@login_required
def change_password(request):
    if request.method == "GET":
        form = CustomPasswordChangeForm(request.user)
        return render(
            request , "login/password_change.html",
            {"form":form}
        )
    elif request.method == "POST":
        form = CustomPasswordChangeForm(request.user , request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect(reverse("login:detail"))
        else :
            return render(
                request , 'login/password_change.html',
                {'form':form  , 'errorMessage' : '패스워드를 다시 입력하세요.'}
            )


#######id 찾기 ###########
from .forms import RecoveryIdForm
from django.views.generic import View


class RecoveryIdView(View):
    template_name = 'login/user_base.html'
    form_class = RecoveryIdForm

    def get(self, request):
        if request.method=='GET':
            form = self.form_class(None)
        return render(request, self.template_name, { 'form':form, })

from django.http import HttpResponse
import json
from django.core.serializers.json import DjangoJSONEncoder
from .models import User


def ajax_find_id_view(request):
    name = request.POST.get('name')
    email = request.POST.get('email')
    result_id = User.objects.get(name=name, email=email)
       
    return HttpResponse(json.dumps({"result_id": result_id.user_id}, cls=DjangoJSONEncoder), content_type = "application/json")

Lockers/login/templates/login/create.html
{% extends "layout.html" %}
{% load django_bootstrap5 %}

{% block title %}가입{%endblock title%}
{%block contents%}
<style>
    .form-container {
        background: rgba(255, 255, 255, 0.8);
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        margin-top: 50px;
    }
    .form-title {
        margin-bottom: 20px;
    }
    .form-label {
        font-weight: bold;
    }
    .btn-custom {
        background-color: #007bff;
        border-color: #007bff;
        color: white;
        width: 100%;
        padding: 10px;
        font-size: 16px;
        border-radius: 5px;
    }
</style>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="form-container">
                <h2 class="text-center form-title">회원가입</h2>
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    
                    <!-- 저장 버튼 -->
                       
                    <div class="mt-3">
                        <button type = "submit" , class="btn btn-custom">가입</button>
                    </div>
                    <div class="mt-3">
                        <button type = "reset" , class="btn btn-custom">초기화</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{%endblock contents%}

Lockers/login/templates/login/detail.html
{%extends "layout.html"%}
{% load django_bootstrap5 %}

{%block title%}회원정보조회{% endblock title%}
{% block contents %}
<style>
    body {
        background-image: url('/static/path_to_your_background_image.jpg'); /* 배경 이미지 경로로 변경 */
        background-size: cover;
        background-position: center;
    }
    .form-container {
        background: rgba(255, 255, 255, 0.8);
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        margin-top: 50px;
    }
    .form-title {
        margin-bottom: 20px;
    }
    .form-label {
        font-weight: bold;
    }
    .btn-custom {
        background-color: #007bff;
        border-color: #007bff;
        color: white;
        width: 100%;
        padding: 10px;
        font-size: 16px;
        border-radius: 5px;
    }
</style>
</head>
<body>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="form-container">
                <h2 class="text-center form-title">프로필 정보</h2>
                <form method="post">
                    {% csrf_token %}

                    <!-- 사용자 정보 섹션 -->
                    <div class="mb-3 row">
                        <label for="username" class="col-sm-5 col-form-label">ID</label>
                        <div class="col-sm-5">
                        {{ object.username }}
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label for="name" class="col-sm-5 col-form-label">이름</label>
                        <div class="col-sm-5">
                        {{ object.name }}
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label for="email" class="col-sm-5 col-form-label">E-Mail</label>
                        <div class="col-sm-5">
                        {{ object.email }}
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label for="phone" class="col-sm-5 col-form-label">휴대폰 번호</label>
                        <div class="col-sm-5">
                        {{ object.phone }}
                        </div>
                    </div>

                    <div class="mt-3">
                        <a href="{% url 'login:update' %}" class="btn btn-custom">정보수정</a>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock contents %}

Lockers/login/templates/login/login.html
<!-- templates/account/login.html -->
{% extends 'layout.html' %}
{% load django_bootstrap5 %}

{% block title%}로그인{% endblock title%}
{% block contents %}
{% if errorMessage != None %}
    <span class="text-danger">{{errorMessage}}</span>
{% endif %}
<style>
    .form-container {
        background: rgba(255, 255, 255, 0.8);
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        margin-top: 50px;
    }
    .form-title {
        margin-bottom: 20px;
    }
    .form-label {
        font-weight: bold;
    }
    .btn-custom {
        background-color: #007bff;
        border-color: #007bff;
        color: white;
        width: 100%;
        padding: 10px;
        font-size: 16px;
        border-radius: 5px;
    }
</style>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="form-container">
                <h2 class="text-center form-title">로그인</h2>
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    
                    <!-- 저장 버튼 -->
                       
                    <div class ="mb-3 row">
                        <button type="submit" class="btn btn-custom">로그인</button>
                    </div>
                    <div class ="mb-3 row">
                        <a href = "{% url 'login:user_base' %}" class="btn btn-custom">id찾기</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock contents%}

Lockers/login/templates/login/loginhome.html
<!-- templates/account/login.html -->
{% extends 'layout.html' %}
{% load django_bootstrap5 %}

{% block title%}홈 화면{% endblock title%}
{% block contents %}
{% if errorMessage != None %}
    <span class="text-danger">{{errorMessage}}</span>
{% endif %}
<form method="post">
    {% csrf_token %}
    <style>
        
        .content {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            text-align: center;
            display: flex;
            flex-direction: column; /* 버튼들을 세로로 정렬 */
            align-items: center;    /* 가운데 정렬 */
        }
        .btn-group {
            display: flex;
            flex-direction: column; /* 버튼 그룹을 세로로 정렬 */
            align-items: center;
        }
        .btn-group a {
            display: block;
            margin-bottom: 15px; /* 각 버튼 간의 간격을 설정 */
            width: 200px; /* 버튼 너비 설정 */
            text-align: center;
        }
        h1 {
        margin-bottom: 20px;
        position: relative;
        font-size: 30pt;
        top: -90px; /* 이 값을 조정하여 LOCKERs의 위치를 올리세요 */
        color: blue;
        }
    </style>
    
    <div class="background-image"></div>
    <div class="content">
        <h1>LOCKERs</h1>
        <div class="btn-group">
            <a href="{% url 'login:detail' %}" class="btn btn-primary">회원정보조회</a>
            <a href="#" class="btn btn-primary">Locker예약</a>
            <a href="#" class="btn btn-primary">Locker조회</a>
            <a href="#" class="btn btn-primary">택배예약</a>
            <a href="#" class="btn btn-primary">택배조회</a>
        </div>
    </div>
    
    
    
</form> 
{% endblock contents%}

Lockers/login/templates/login/password_change.html
{% extends 'layout.html' %}
{% load django_bootstrap5 %}

{% block title%}수정{% endblock title%}
{% block contents %}
<style>
    .form-container {
        background: rgba(255, 255, 255, 0.8);
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        margin-top: 50px;
    }
    .form-title {
        margin-bottom: 20px;
    }
    .form-label {
        font-weight: bold;
    }
    .btn-custom {
        background-color: #007bff;
        border-color: #007bff;
        color: white;
        width: 100%;
        padding: 10px;
        font-size: 16px;
        border-radius: 5px;
    }
</style>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="form-container">
                <h2 class="text-center form-title">비밀번호 업데이트</h2>
                <form method="post">
                    {% csrf_token %}
                    
                    {% bootstrap_form form %}
                    
                    <!-- 저장 버튼 -->
                    <button type="submit" class="btn btn-custom">저장</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock contents%}

Lockers/login/templates/login/update.html
{% extends 'layout.html' %}
{% load django_bootstrap5 %}

{% block title%}수정{% endblock title%}
{% block contents %}
<style>
    .form-container {
        background: rgba(255, 255, 255, 0.8);
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        margin-top: 50px;
    }
    .form-title {
        margin-bottom: 20px;
    }
    .form-label {
        font-weight: bold;
    }
    .btn-custom {
        background-color: #007bff;
        border-color: #007bff;
        color: white;
        width: 100%;
        padding: 10px;
        font-size: 16px;
        border-radius: 5px;
    }
</style>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="form-container">
                <h2 class="text-center form-title">프로필 및 비밀번호 업데이트</h2>
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    
                    <!-- 저장 버튼 -->
                    <div class ="mb-3 row">
                        <a href="{%url 'login:password_change'%}" class="btn btn-custom">비밀번호 변경</a>
                    </div>    
                    <div class ="mb-3 row">
                        <button type="submit" class="btn btn-custom">저장</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock contents%}

Lockers/login/templates/login/user_base.html
{% extends 'layout.html' %}
{% load django_bootstrap5 %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

{% block title%}아이디 찾기{% endblock title%}

{% block contents%}
<div>
    {% csrf_token %}
    <label name="label_name" for="{{ form_id.name.id_for_label }}">{{ form.name.label }}</label>
    {{ form.name }}
    <label name="label_email" for="{{ form_id.email.id_for_label }}">{{ form.email.label }}</label>
    {{ form.email }}
    <small>
        등록하신 이름과 메일주소가 일치해야 합니다.
    </small>
    <div>
        <button id="find_id" name="recovery_id">아이디찾기</button>
    </div>

    <div id="result_id"></div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#find_id').click(function () {
                var name = $("#form_name").val();
                var email = $("#form_email").val();

                $.ajax({
                    type: "POST",
                    url: "/users/recovery/id/find/",
                    dataType: "json",
                    data: {
                        'name': name,
                        'email': email,
                        'csrfmiddlewaretoken': '{{csrf_token}}',
                    },
                    success: function (response) {
                        $('#result_id').replaceWith(
                            '<div id="result_id"><hr><div><span>입력된 정보로 가입된 아이디는 </span><span id="result_id">' +
                                response.result_id +'</span><span> 입니다.</span></div><hr></div>')
                    },
                    error: function () {
                        if (name == "" || email == "") {
                            alert('이름와 이메일을 입력해주세요.');
                        } else {
                            alert('입력하신 정보가 일치하지 않거나 존재하지 않습니다.');
                        }
                    },
                });
            })
        });
    </script>
</div>
{% endblock contents%}

Lockers/templates/home.html
{% extends "layout.html" %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block contents %}
<style>
    .content {
                position: absolute;
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%);
                text-align: center;
                color: blue;
            }
    h1 {
        margin-bottom: 20px;
        position: relative;
        font-size: 30pt;
        top: -90px; /* 이 값을 조정하여 LOCKERs의 위치를 올리세요 */
    }
</style>
<div class="content">
    <h1>LOCKERs</h1>
    <div class="mt-3">
        <a href="{% url 'login:login' %}" class="btn btn-primary">로그인</a>
    </div>
    <div class="mt-3">
        <a href="{% url 'login:create' %}" class="btn btn-primary">회원가입</a>
    </div>
</div>
{% endblock contents %}

Lockers/templates/layout.html
{# layer.html #}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Document{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="container mt-4">
        <style>
            body {
                margin: 0;
                padding: 0;
            }
            .background-image {
                background-image: url('/static/imgs/main_img.webp');
                background-size: cover;
                background-position: center;
                background-repeat: no-repeat;
                width: 100vw;
                height: 100vh;
                position: fixed;
                top: 0;
                left: 0;
                z-index: -1;
            }
            
        </style>
        <div class="background-image"></div>
        {% block contents%}{% endblock contents%}
</body>
</html>